name: Run Python Script Daily

on:
  schedule:
    # Run at 00:00 UTC every day
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pandas

    - name: Run script
      run: |
        python abc.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: csv-files
        path: '*.csv'
